### ISSUE TITLE
Add an alternative format to QC

### ISSUE THREAD

**Issue by G2Pavon** [G2Pavon/studiomdlPlusPlus#22]
Alternatives:

JSON:

```json
{
  "modelname": "hostage.mdl",
  "cd": ".",
  "cdtexture": ["./maps_8bit"],
  "eyeposition": [0, 0, 60],
  "body": {
    "name": "studio",
    "model": "hostage_fix04"
  },
  "texturegroup": {
    "name": "group1",
    "textures": [
      ["hostage_template1.bmp", "face-unwrap1.bmp"],
      ["hostage_template2.bmp", "face-unwrap2.bmp"]
    ]
  },
  "controllers": [
    {
      "id": 0,
      "bone": "Bip02 Head",
      "axis": "XR",
      "min": -60,
      "max": 60
    }
  ],
  "hitboxes": [
    {
      "group": 6,
      "bone": "Bip02 L Leg",
      "min": [0, -5.69, -3.55],
      "max": [18.71, 3.61, 3.43]
    },
    {
      "group": 6,
      "bone": "Bip02 L Leg1",
      "min": [0, -3.77, -2.97],
      "max": [16.96, 2.21, 2.41]
    }
  ],
  "sequences": [
    {
      "name": "walk",
      "animation": "./anims/walk",
      "fps": 20,
      "loop": true,
      "activity": {
        "name": "ACT_WALK",
        "weight": 1
      },
      "motion": "LX",
      "events": [
        {
          "id": 1004,
          "frame": 0,
          "sound": "common/npc_step1.wav"
        },
        {
          "id": 1004,
          "frame": 8,
          "sound": "common/npc_step3.wav"
        }
      ]
    }
  ]
}


```

YAML:

```YAML

modelname: "hostage.mdl"
cd: "/home/gaspar/Programming/studiomdlPlusPlus/build/bin/hostage"
cdtexture:
  - "./maps_8bit"

eyeposition: [0, 0, 60]

body:
  name: "studio"
  model: "hostage_fix04"

texturegroup:
  name: "group1"
  textures:
    - ["hostage_template1.bmp", "face-unwrap1.bmp"]
    - ["hostage_template2.bmp", "face-unwrap2.bmp"]

controllers:
  - id: 0
    bone: "Bip02 Head"
    axis: "XR"
    min: -60
    max: 60

hitboxes:
  - group: 6
    bone: "Bip02 L Leg"
    min: [0, -5.69, -3.55]
    max: [18.71, 3.61, 3.43]

  - group: 6
    bone: "Bip02 L Leg1"
    min: [0, -3.77, -2.97]
    max: [16.96, 2.21, 2.41]

sequences:
  - name: "walk"
    animation: "./anims/walk"
    fps: 20
    loop: true
    activity:
      name: "ACT_WALK"
      weight: 1
    motion: "LX"
    events:
      - id: 1004
        frame: 0
        sound: "common/npc_step1.wav"
      - id: 1004
        frame: 8
        sound: "common/npc_step3.wav"

```
